# Program name.
PROG	=	test_monoclock

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	monoclock.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	test_monoclock
	./test_monoclock

.include <bsd.prog.mk>
