.POSIX:

SRCS=	main.c monoclock.c warnp.c

IDIRS=	-I ../../util

test_monoclock:	${SRCS:.c=.o}
	${CC} ${CFLAGS} -o test_monoclock ${SRCS:.c=.o} ${LDADD_POSIX}

main.o:	main.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -D__BSD_VISIBLE -c main.c -o main.o

monoclock.o:	../../util/monoclock.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../util/monoclock.c -o monoclock.o

warnp.o:	../../util/warnp.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../util/warnp.c -o warnp.o

clean:
	rm -f test_monoclock ${SRCS:.c=.o}
