# Program name.
PROG	=	test_setuidgid

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_setuidgid $$(id -u):$$(id -g)

.include <bsd.prog.mk>
