# Program name.
PROG	=	test_crypto_aes

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Library code required
LDADD_REQ	= -lcrypto

# Main test code
SRCS	=	main.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport
IDIRS	+=	-I${LIBCPERCIVA_DIR}/crypto
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_crypto_aes -x

# This depends on "all", but we don't want to see any output from that.
perftest:
	@${MAKE} all > /dev/null
	@printf "# nblks\tbsize\ttime\tspeed\n"
	@./test_crypto_aes -t |						\
	    grep "blocks" |						\
	    awk '{ printf "%d\t%d\t%.6f\t%.6f\n", $$1, $$5, $$6, $$8}'

.include <bsd.prog.mk>
