# Program name.
PROG	=	test_sha1

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	sha1.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	hexify.c
SRCS	+=	insecure_memzero.c
SRCS	+=	monoclock.c
SRCS	+=	perftest.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_sha1 -x

# This depends on "all", but we don't want to see any output from that.
perftest:
	@${MAKE} all > /dev/null
	@printf "# nblks\tbsize\ttime\tspeed\n"
	@./test_sha1 -t |						\
	    grep "blocks" |						\
	    awk '{ printf "%i\t%i\t%.6f\t%.1f\n", $$1, $$5, $$6, $$8}'

.include <bsd.prog.mk>
