#!/bin/sh

D=$1
MAKEBSD=$2
CFLAGS_HARDCODED=$3

OUT=${D}/Makefile

echo '.POSIX:' > $OUT
echo '# AUTOGENERATED FILE, DO NOT EDIT' >> $OUT
( cd ${D} && printf 'PROG=' && ${MAKEBSD} -V PROG ) >> $OUT
( cd ${D} && printf 'MAN1=' && ${MAKEBSD} -V MAN1 ) >> $OUT
( cd ${D} && printf 'SRCS=' && ${MAKEBSD} -V SRCS | sed -e 's| cpusupport-config.h||' ) >> $OUT
( cd ${D} && printf 'IDIRS=' && ${MAKEBSD} -V IDIRS ) >> $OUT
( cd ${D} && printf 'LDADD_REQ=' && ${MAKEBSD} -V LDADD_REQ ) >> $OUT
( cd ${D} && printf 'SUBDIR_DEPTH=' && ${MAKEBSD} -V SUBDIR_DEPTH ) >> $OUT
( cd ${D} && printf "RELATIVE_DIR=$D\n" ) >> $OUT
if [ `cd ${D} && ${MAKEBSD} -V NOINST` ]; then
	cat Makefile.prog |				\
	    perl -0pe 's/(install:.*?)\n\n//s' >> $OUT
else
	cat Makefile.prog >> $OUT
fi
rm -f cpusupport-config.h
touch cpusupport-config.h
( cd ${D} && ${MAKEBSD} -V SRCS |			\
    sed -e 's| cpusupport-config.h||' |			\
    tr ' ' '\n' |					\
    sed -E 's/.c$/.o/' |				\
    while read F; do
	S=`${MAKEBSD} source-${F}`
	CF=`${MAKEBSD} cflags-${F}`
	IDIRS=`${MAKEBSD} -V IDIRS`
	SUBDIR_DEPTH=`${MAKEBSD} -V SUBDIR_DEPTH`
	echo `${CPP} ${S} -std=c99 -DCPUSUPPORT_CONFIG_FILE=\"cpusupport-config.h\" -I${SUBDIR_DEPTH} ${IDIRS} -MM -MT ${F}` \
		| sed -e 's| \\ | |g'
	echo "	\${CC} \${CFLAGS_POSIX} ${CFLAGS_HARDCODED} ${CF} -I${SUBDIR_DEPTH} \${IDIRS} \${CPPFLAGS} \${CFLAGS} -c ${S} -o ${F}"
    done ) >> $OUT
if grep -q "test:" ${D}/Makefile.BSD ; then
	printf "\n" >> $OUT
	( cd ${D} && awk '/test:/, /^$/' Makefile.BSD |		\
	    awk '$1' ) >> $OUT
fi
if grep -q "all_extra:" ${D}/Makefile.BSD ; then
	printf "\n" >> $OUT
	( cd ${D} && awk '/all_extra:/, /^$/' Makefile.BSD |	\
	    awk '$1' ) >> $OUT
	( cd ${D} && sed -e					\
	    's/${MAKE} ${PROG}/${MAKE} ${PROG} all_extra/'	\
	    Makefile > Makefile.new )
	( cd ${D} && mv Makefile.new Makefile )
fi
if grep -q "clean_extra:" ${D}/Makefile.BSD ; then
	printf "\n" >> $OUT
	( cd ${D} && awk '/clean_extra:/, /^$/' Makefile.BSD |	\
	    awk '$1' ) >> $OUT
	( cd ${D} && awk					\
	    '/clean:/ {print $0 "\tclean_extra";next}{print}'	\
	    Makefile > Makefile.new )
	( cd ${D} && mv Makefile.new Makefile )
fi
rm -f cpusupport-config.h
