#!/bin/sh

D=$1
MAKEBSD=$2
CFLAGS_HARDCODED=$3

OUT=Makefile

cd ${D}
SUBDIR_DEPTH=`${MAKEBSD} -V SUBDIR_DEPTH`
echo '.POSIX:' > $OUT
echo '# AUTOGENERATED FILE, DO NOT EDIT' >> $OUT
( printf 'PROG=' && ${MAKEBSD} -V PROG ) >> $OUT
( printf 'MAN1=' && ${MAKEBSD} -V MAN1 ) >> $OUT
( printf 'SRCS=' && ${MAKEBSD} -V SRCS | sed -e 's| cpusupport-config.h||' ) >> $OUT
( printf 'IDIRS=' && ${MAKEBSD} -V IDIRS ) >> $OUT
( printf 'LDADD_REQ=' && ${MAKEBSD} -V LDADD_REQ ) >> $OUT
( printf 'SUBDIR_DEPTH=' && ${MAKEBSD} -V SUBDIR_DEPTH ) >> $OUT
( printf "RELATIVE_DIR=$D\n" ) >> $OUT
if [ `${MAKEBSD} -V NOINST` ]; then
	cat ${SUBDIR_DEPTH}/Makefile.prog |		\
	    perl -0pe 's/(install:.*?)\n\n//s' >> $OUT
else
	cat ${SUBDIR_DEPTH}/Makefile.prog >> $OUT
fi
rm -f ${SUBDIR_DEPTH}/cpusupport-config.h
touch ${SUBDIR_DEPTH}/cpusupport-config.h
( ${MAKEBSD} -V SRCS |					\
    sed -e 's| cpusupport-config.h||' |			\
    tr ' ' '\n' |					\
    sed -E 's/.c$/.o/' |				\
    while read F; do
	S=`${MAKEBSD} source-${F}`
	CF=`${MAKEBSD} cflags-${F}`
	IDIRS=`${MAKEBSD} -V IDIRS`
	echo `${CPP} ${S} -std=c99 -DCPUSUPPORT_CONFIG_FILE=\"cpusupport-config.h\" -I${SUBDIR_DEPTH} ${IDIRS} -MM -MT ${F}` \
		| sed -e 's| \\ | |g'
	echo "	\${CC} \${CFLAGS_POSIX} ${CFLAGS_HARDCODED} ${CF} -I${SUBDIR_DEPTH} \${IDIRS} \${CPPFLAGS} \${CFLAGS} -c ${S} -o ${F}"
    done ) >> $OUT
if grep -q "test:" Makefile.BSD ; then
	printf "\n" >> $OUT
	( awk '/test:/, /^$/' Makefile.BSD |			\
	    awk '$1' ) >> $OUT
fi
if grep -q "all_extra:" Makefile.BSD ; then
	printf "\n" >> $OUT
	( awk '/all_extra:/, /^$/' Makefile.BSD |		\
	    awk '$1' ) >> $OUT
	( sed -e						\
	    's/${MAKE} ${PROG}/${MAKE} ${PROG} all_extra/'	\
	    Makefile > Makefile.new )
	( mv Makefile.new Makefile )
fi
if grep -q "clean_extra:" Makefile.BSD ; then
	printf "\n" >> $OUT
	( awk '/clean_extra:/, /^$/' Makefile.BSD |		\
	    awk '$1' ) >> $OUT
	( awk							\
	    '/clean:/ {print $0 "\tclean_extra";next}{print}'	\
	    Makefile > Makefile.new )
	( mv Makefile.new Makefile )
fi
rm -f ${SUBDIR_DEPTH}/cpusupport-config.h
