# Program name.
PROG	=	test_elasticarray

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c
SRCS	+=	elasticarray_perftest.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_elasticarray

.include <bsd.prog.mk>
