# Program name.
PROG	=	test_sha256

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	sha256.c
SRCS	+=	sha256_shani.c
SRCS	+=	sha256_sse2.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_shani.c
SRCS	+=	cpusupport_x86_sse2.c
SRCS	+=	cpusupport_x86_ssse3.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	hexify.c
SRCS	+=	insecure_memzero.c
SRCS	+=	monoclock.c
SRCS	+=	perftest.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

cflags-sha256_shani.o:
	@echo '$${CFLAGS_X86_SHANI} $${CFLAGS_X86_SSSE3}'

cflags-sha256_sse2.o:
	@echo '$${CFLAGS_X86_SSE2}'

test:	all
	./test_sha256 -x

# This depends on "all", but we don't want to see any output from that.
perftest:
	@${MAKE} all > /dev/null
	@printf "# nblks\tbsize\ttime\tspeed\n"
	@./test_sha256 -t |						\
	    grep "blocks" |						\
	    awk '{ printf "%i\t%i\t%.6f\t%.6f\n", $$1, $$5, $$6, $$8}'

.include <bsd.prog.mk>
