# Program name.
PROG	=	test_sha256

# Don't install it.
NOINST	= 	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	sha256.c
SRCS	+=	sha256_shani.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_shani.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	hexify.c
SRCS	+=	insecure_memzero.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

cflags-sha256_shani.o:
	@echo '$${CFLAGS_X86_SHANI}'

test:	test_sha256
	@./test_sha256 -x

.include <bsd.prog.mk>
