.POSIX:

SRCS=	main.c sha256.c getopt.c hexify.c insecure_memzero.c warnp.c

IDIRS=	-I ../../alg -I ../../util

test_sha256:	${SRCS:.c=.o}
	${CC} ${CFLAGS} -o test_sha256 ${SRCS:.c=.o} ${LDADD_POSIX}

main.o:	main.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -D__BSD_VISIBLE -c main.c -o main.o

sha256.o:	../../alg/sha256.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../alg/sha256.c -o sha256.o

getopt.o:	../../util/getopt.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../util/getopt.c -o getopt.o

hexify.o:	../../util/hexify.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../util/hexify.c -o hexify.o

insecure_memzero.o:	../../util/insecure_memzero.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../util/insecure_memzero.c -o insecure_memzero.o

warnp.o:	../../util/warnp.c
	${CC} ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${IDIRS} ${CFLAGS_POSIX} -c ../../util/warnp.c -o warnp.o

clean:
	rm -f test_sha256 ${SRCS:.c=.o}
