# Program name.
PROG	=	test_crypto_aesctr

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Library code required
LDADD_REQ	= -lcrypto

# Main test code
SRCS	=	main.c

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_aesni.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Crypto
.PATH.c	:	${LIBCPERCIVA_DIR}/crypto
SRCS	+=	crypto_aes.c
SRCS	+=	crypto_aes_aesni.c
SRCS	+=	crypto_aesctr.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/crypto

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	hexify.c
SRCS	+=	insecure_memzero.c
SRCS	+=	monoclock.c
SRCS	+=	perftest.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

cflags-crypto_aes_aesni.o:
	@echo '$${CFLAGS_X86_AESNI}'

test:	all
	./test_crypto_aesctr -x

# This depends on "all", but we don't want to see any output from that.
perftest:
	@${MAKE} all > /dev/null
	@printf "# nblks\tbsize\ttime\tspeed\n"
	@./test_crypto_aesctr -t |					\
	    grep "blocks" |						\
	    awk '{ printf "%i\t%i\t%.6f\t%.1f\n", $$1, $$5, $$6, $$8}'

.include <bsd.prog.mk>
