# This test only makes sense when it's run from the top-level directory,
# due to a combination of the "generate top-level flag files" and the "generate
# new Makefiles to test compiling headers individually".

# Program name.
PROG	=	test_buildsingles

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Include libcperciva directories
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg
IDIRS	+=	-I${LIBCPERCIVA_DIR}/aws
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport
IDIRS	+=	-I${LIBCPERCIVA_DIR}/crypto
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I${LIBCPERCIVA_DIR}/external/queue
IDIRS	+=	-I${LIBCPERCIVA_DIR}/http
IDIRS	+=	-I${LIBCPERCIVA_DIR}/netbuf
IDIRS	+=	-I${LIBCPERCIVA_DIR}/network
IDIRS	+=	-I${LIBCPERCIVA_DIR}/network_ssl
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

all_extra:
	${MAKE} -f Makefile-headers CFLAGS_POSIX="${CFLAGS_POSIX}" CPPFLAGS="${CPPFLAGS}" CFLAGS="${CFLAGS}" IDIRS="${IDIRS}" buildsingles

clean_extra:
	${MAKE} -f Makefile-headers clean

test:
	true

.include <bsd.prog.mk>
