# This test only makes sense when it's run from the top-level directory,
# due to a combination of the "generate top-level flag files" and the "generate
# new Makefiles to test compiling headers individually".

# Program name.
PROG	=	test_buildsingles

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

all_extra:
	${MAKE} -f Makefile-headers CFLAGS_POSIX="${CFLAGS_POSIX}" CFLAGS="${CFLAGS}" buildsingles

clean_extra:
	${MAKE} -f Makefile-headers clean

test:
	true

.include <bsd.prog.mk>
