.POSIX:

HEADERS=\
	crc32c.h crc32c_sse42.h md5.h sha1.h sha256.h \
	aws_readkeys.h aws_sign.h \
	cpusupport.h \
	crypto_aes.h crypto_aes_aesni.h crypto_aesctr.h crypto_dh.h \
		crypto_dh_group14.h crypto_entropy.h crypto_entropy_rdrand.h \
		crypto_verify_bytes.h \
	elasticarray.h elasticqueue.h mpool.h ptrheap.h seqptrmap.h \
		timerqueue.h \
	events.h events_internal.h \
	network.h \
	asprintf.h b64encode.h ctassert.h daemonize.h entropy.h getopt.h \
		hexify.h humansize.h imalloc.h insecure_memzero.h json.h \
		monoclock.h noeintr.h parsenum.h readpass.h setuidgid.h \
		sock.h sock_internal.h sock_util.h sysendian.h ttyfd.h warnp.h

buildsingles: Makefile.inc2
	${MAKE} -f Makefile.inc2 CFLAGS="${CFLAGS}"	\
		CFLAGS_POSIX="${CFLAGS_POSIX}" LDADD_POSIX="${LDADD_POSIX}" all

Makefile.inc2: Makefile.inc1
	printf "all: ${HEADERS:.h=-main}\n\t: > test_buildsingles\n\n"	\
	    > Makefile.inc2
	for HN in ${HEADERS}; do				\
		H=`ls ../../*/$${HN}`;				\
		echo "$${HN%.h}-main: $${H}";			\
		echo "	${CC} -DHEADER=\"\\\"$${H}\\\"\" ${CFLAGS} -D_POSIX_C_SOURCE=200809L ${CFLAGS_POSIX} -o $${HN%.h}-main main.c ${LDADD_POSIX}";	\
		echo;						\
	done >> Makefile.inc2

clean:
	rm -f Makefile.inc2 ${HEADERS:.h=-main}
