# Program name.
PROG	=	buildall

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Library code required
LDADD_REQ	= -lcrypto

# Main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	crc32c.c
SRCS	+=	crc32c_sse42.c
SRCS	+=	md5.c
SRCS	+=	sha1.c
SRCS	+=	sha256.c
SRCS	+=	sha256_shani.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# Amazon Web Services
.PATH.c	:	${LIBCPERCIVA_DIR}/aws
SRCS	+=	aws_readkeys.c
SRCS	+=	aws_sign.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/aws

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_aesni.c
SRCS	+=	cpusupport_x86_crc32_64.c
SRCS	+=	cpusupport_x86_rdrand.c
SRCS	+=	cpusupport_x86_shani.c
SRCS	+=	cpusupport_x86_sse2.c
SRCS	+=	cpusupport_x86_ssse3.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Crypto code
.PATH.c	:	${LIBCPERCIVA_DIR}/crypto
SRCS	+=	crypto_aes.c
SRCS	+=	crypto_aes_aesni.c
SRCS	+=	crypto_aesctr.c
SRCS	+=	crypto_dh.c
SRCS	+=	crypto_dh_group14.c
SRCS	+=	crypto_entropy.c
SRCS	+=	crypto_entropy_rdrand.c
SRCS	+=	crypto_verify_bytes.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/crypto

# Data structures
.PATH.c	:	${LIBCPERCIVA_DIR}/datastruct
SRCS	+=	elasticarray.c
SRCS	+=	elasticqueue.c
SRCS	+=	ptrheap.c
SRCS	+=	seqptrmap.c
SRCS	+=	timerqueue.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct

# Event loop
.PATH.c	:	${LIBCPERCIVA_DIR}/events
SRCS	+=	events_immediate.c
SRCS	+=	events_network.c
SRCS	+=	events_network_selectstats.c
SRCS	+=	events_timer.c
SRCS	+=	events.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events

# Event-driven networking
.PATH.c	:	${LIBCPERCIVA_DIR}/network
SRCS	+=	network_accept.c
SRCS	+=	network_connect.c
SRCS	+=	network_read.c
SRCS	+=	network_write.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/network

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	asprintf.c
SRCS	+=	b64encode.c
SRCS	+=	daemonize.c
SRCS	+=	entropy.c
SRCS	+=	getopt.c
SRCS	+=	hexify.c
SRCS	+=	humansize.c
SRCS	+=	insecure_memzero.c
SRCS	+=	json.c
SRCS	+=	monoclock.c
SRCS	+=	noeintr.c
SRCS	+=	readpass.c
SRCS	+=	readpass_file.c
SRCS	+=	setuidgid.c
SRCS	+=	sock.c
SRCS	+=	sock_util.c
SRCS	+=	ttyfd.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

cflags-crc32c_sse42.o:
	@echo '$${CFLAGS_X86_CRC32_64}'

cflags-crypto_aes_aesni.o:
	@echo '$${CFLAGS_X86_AESNI}'

cflags-crypto_entropy_rdrand.o:
	@echo '$${CFLAGS_X86_RDRAND}'

cflags-sha256_shani.o:
	@echo '$${CFLAGS_X86_SHANI} $${CFLAGS_X86_SSSE3}'

test:	buildall
	true

.include <bsd.prog.mk>
