# Program name.
PROG	=	buildall

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Library code required
LDADD_REQ	= -lcrypto

# Main test code
SRCS	=	main.c

test:	buildall
	true

.include <bsd.prog.mk>
