# Program name.
PROG	=	test_json

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS=	main.c

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	json.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

test:	all
	@./test_json

.include <bsd.prog.mk>
