# Program name.
PROG	=	test_fork_func

# Don't install it.
NOINST	=	1

# Library code required
LDADD_REQ	=	-lpthread

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c
SRCS	+=	check_exec.c
SRCS	+=	check_exit.c
SRCS	+=	check_order.c
SRCS	+=	check_perftest.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

.include <bsd.prog.mk>
