# Program name.
PROG	=	test_humansize

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	asprintf.c
SRCS	+=	humansize.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_humansize

.include <bsd.prog.mk>
