# Program name.
PROG	=	test_optional_mutex_normal

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../../..

# Main test code
.PATH.c	:	..
SRCS	=	main.c

# Handle optional_mutex
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	optional_mutex.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./${PROG}

.include <bsd.prog.mk>
