# Program name.
PROG	=	test_events

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c
SRCS	+=	events_counter.c
SRCS	+=	events_interrupter.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test-events.sh

.include <bsd.prog.mk>
