# Program name.
PROG	=	test_parsenum

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Library code required
LDADD_REQ	= -lm

# Main test code
SRCS	=	main.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_parsenum

.include <bsd.prog.mk>
