# Program name.
PROG	=	test_noeintr_close_pthread

# Don't install it.
NOINST	=	1

# Library code required
LDADD_REQ	=	-lpthread

# Useful relative directories
LIBCPERCIVA_DIR	=	../../..
NOEINTR_CLOSE_SHARED	=	..

# Main test code
SRCS	=	main.c
SRCS	+=	open_close_threaded.c

# Shared test code for noeintr_close()
.PATH.c :	${NOEINTR_CLOSE_SHARED}
SRCS	+=	open_close.c
IDIRS	+=	-I${NOEINTR_CLOSE_SHARED}

# Handle optional_mutex
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	optional_mutex.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# Linking library-dependent functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	noeintr_close.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# Special test-only define
CFLAGS.noeintr_close.c=	-DNOEINTR_CLOSE_TESTING

.include <bsd.prog.mk>
