# Program name.
PROG	=	test_mpool

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Data structures
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	monoclock.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_mpool.sh

.include <bsd.prog.mk>
