# Program name.
PROG	=	test_events_network_server

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../../..
EVENTS_TEST_DIR	=	..

# Main test code
SRCS	=	main.c

# Event-test code
.PATH.c	:	${EVENTS_TEST_DIR}
SRCS	+=	events_counter.c
SRCS	+=	events_interrupter.c
IDIRS	+=	-I${EVENTS_TEST_DIR}

# Data structures
.PATH.c	:	${LIBCPERCIVA_DIR}/datastruct
SRCS	+=	elasticarray.c
SRCS	+=	ptrheap.c
SRCS	+=	timerqueue.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct

# Event loop
.PATH.c	:	${LIBCPERCIVA_DIR}/events
SRCS	+=	events_immediate.c
SRCS	+=	events_network.c
SRCS	+=	events_network_selectstats.c
SRCS	+=	events_timer.c
SRCS	+=	events.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	monoclock.c
SRCS	+=	sock.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

.include <bsd.prog.mk>
