# Program name.
PROG	=	test_crypto_entropy

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	sha256.c
SRCS	+=	sha256_shani.c
SRCS	+=	sha256_sse2.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_rdrand.c
SRCS	+=	cpusupport_x86_shani.c
SRCS	+=	cpusupport_x86_sse2.c
SRCS	+=	cpusupport_x86_ssse3.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Crypto code
.PATH.c	:	${LIBCPERCIVA_DIR}/crypto
SRCS	+=	crypto_entropy.c
SRCS	+=	crypto_entropy_rdrand.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/crypto

# Utility functions
.PATH.c :	${LIBCPERCIVA_DIR}/util
SRCS	+=	entropy.c
SRCS	+=	insecure_memzero.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

cflags-crypto_entropy_rdrand.o:
	@echo '$${CFLAGS_X86_RDRAND}'

cflags-sha256_shani.o:
	@echo '$${CFLAGS_X86_SHANI} $${CFLAGS_X86_SSSE3}'

cflags-sha256_sse2.o:
	@echo '$${CFLAGS_X86_SSE2}'

test:	all
	./test_crypto_entropy

.include <bsd.prog.mk>
