# Program name.
PROG	=	test_crypto_entropy

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/crypto
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	all
	./test_crypto_entropy

.include <bsd.prog.mk>
