# Program name.
PROG	=	test_crc32

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# Main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	crc32c.c
SRCS	+=	crc32c_sse42.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_crc32_64.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	monoclock.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

cflags-crc32c_sse42.o:
	@echo '$${CFLAGS_X86_CRC32_64}'

test:	all
	./test_crc32 -x

.include <bsd.prog.mk>
