# Program name.
PROG	=	test_crc32

# Don't install it.
NOINST	= 	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../..

# main test code
SRCS	=	main.c

# Algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	crc32c.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/alg

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

test:	test_crc32
	@./test_crc32 -x

.include <bsd.prog.mk>
